# Opciones de funding para el proyecto
# Descomentar y configurar según necesites

# github: [usuario]
# patreon: usuario
# open_collective: proyecto
# ko_fi: usuario
# custom: ['https://tu-sitio.com/donate', 'https://buymeacoffee.com/usuario']
